### ISSUE TITLE
Problem wiht DATARATE change

### ISSUE THREAD

**Issue by jslee777** [adafruit/Adafruit_Python_ADXL345#1]
ADXL345_DATARATE_100_HZ  = 0x0A is defualt 

To analyze frequency, I need to get the data by 100 Hz. ( 100 times /per sencond)
Problem is that this code is designed by the sleep time of half second in the simple-example.

Though I tried, I can't get them. 
If it is possilbe to get the data by 100Hz per second, please let me know. Thanks

**Comment by kattni** [comment]
This library is no longer supported. We are only supporting CircuitPython libraries. CircuitPython libraries work on supported SBCs with GPIO with the [Adafruit Blinka library](https://github.com/adafruit/Adafruit_Blinka). Please see the [Adafruit CircuitPython ADXL34x library](https://github.com/adafruit/Adafruit_CircuitPython_ADXL34x).
