### ISSUE TITLE
Need python3 version

### ISSUE THREAD

**Issue by vbisbest** [adafruit/Adafruit_Python_ADXL345#2]
Can we get a python3 version of this library?

**Comment by kattni** [comment]
This library is no longer supported. We are only supporting CircuitPython libraries. CircuitPython libraries work on supported SBCs with GPIO with the [Adafruit Blinka library](https://github.com/adafruit/Adafruit_Blinka). Please see the [Adafruit CircuitPython ADXL34x library](https://github.com/adafruit/Adafruit_CircuitPython_ADXL34x).
