### ISSUE TITLE
how to get mutiple sensors data

### ISSUE THREAD

**Issue by Alicture** [adafruit/Adafruit_Python_ADXL345#3]
how to get multiple sensors' data

**Comment by kattni** [comment]
This library is no longer supported. We are only supporting CircuitPython libraries. CircuitPython libraries work on supported SBCs with GPIO with the [Adafruit Blinka library](https://github.com/adafruit/Adafruit_Blinka). Please see the [Adafruit CircuitPython ADXL34x library](https://github.com/adafruit/Adafruit_CircuitPython_ADXL34x).
